# UAPI Header export list
header-y += fc/
header-y += scsi_bsg_fc.h
header-y += scsi_netlink.h
header-y += scsi_netlink_fc.h
header-y += cxlflash_ioctl.h
header-y += scsi.h
header-y += scsi_ioctl.h
header-y += scsi_proto.h
header-y += sg.h
