# Intel pin control drivers

obj-$(CONFIG_PINCTRL_BAYTRAIL)		+= pinctrl-baytrail.o
obj-$(CONFIG_PINCTRL_CHERRYVIEW)	+= pinctrl-cherryview.o
obj-$(CONFIG_PINCTRL_INTEL)		+= pinctrl-intel.o
obj-$(CONFIG_PINCTRL_BROXTON)		+= pinctrl-broxton.o
obj-$(CONFIG_PINCTRL_SUNRISEPOINT)	+= pinctrl-sunrisepoint.o
obj-$(CONFIG_SYNO_DENVERTON)		+= pinctrl-denverton.o
obj-$(CONFIG_SYNO_PINCTRL_LEWISBURG) 	+= pinctrl-lewisburg.o
