dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-synology-DS418.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1293-synology-DS418j.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-synology-DS218play.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-synology-DS118.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-synology-DS218.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
